export const DISPLAY_MODE = "DISPLAY_MODE";

export const REMOVE_TASK = "REMOVE_TASK";

export const ADD_TASK = "ADD_TASK";

export const MAKE_IMPORTANT = "MAKE_IMPORTANT";

export const ADD_TO_DONE = "ADD_TO_DONE";

export const INITIALISE_ALL_TASKS = "INITIALISE_ALL_TASKS";

export const FETCH_DATA = "FETCH_DATA";

export const FETCH_DATA_PENDING = "FETCH_DATA_PENDING";

export const FETCH_DATA_FULFILLED = "FETCH_DATA_FULFILLED";

export const FETCH_DATA_REJECTED = "FETCH_DATA_REJECTED";
