export const DISPLAY_MODE = "DISPLAY_MODE";

export const FETCH_DATA = "FETCH_DATA";

export const FETCH_DATA_PENDING = "FETCH_DATA_PENDING";

export const FETCH_DATA_FULFILLED = "FETCH_DATA_FULFILLED";

export const FETCH_DATA_REJECTED = "FETCH_DATA_REJECTED";

export const DELETE_DATA = "DELETE_DATA";

export const DELETE_DATA_PENDING = "DELETE_DATA_PENDING";

export const DELETE_DATA_FULFILLED = "DELETE_DATA_FULFILLED";

export const DELETE_DATA_REJECTED = "DELETE_DATA_REJECTED";

export const UPDATE_IMPORTANT = "UPDATE_IMPORTANT";

export const UPDATE_IMPORTANT_PENDING = "UPDATE_IMPORTANT_PENDING";

export const UPDATE_IMPORTANT_FULFILLED = "UPDATE_IMPORTANT_FULFILLED";

export const UPDATE_IMPORTANT_REJECTED = "UPDATE_IMPORTANT_REJECTED";

export const UPDATE_DONE = "UPDATE_DONE";

export const UPDATE_DONE_PENDING = "UPDATE_DONE_PENDING";

export const UPDATE_DONE_FULFILLED = "UPDATE_DONE_FULFILLED";

export const UPDATE_DONE_REJECTED = "UPDATE_DONE_REJECTED";

export const ADD_TASK = "ADD_TASK";

export const ADD_TASK_PENDING = "ADD_TASK_PENDING";

export const ADD_TASK_FULFILLED = "ADD_TASK_FULFILLED";

export const ADD_TASK_REJECTED = "ADD_TASK_REJECTED";

export const LOADER_BOOL = "LOADER_BOOL";

